CREATE TABLE users(
    id BIGINT AUTO_INCREMENT NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(120) NOT NULL,
    username VARCHAR(100) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT U_USER_EMAIL UNIQUE (email)
);